// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const configuredSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const configuredSupabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const isHttpUrl = (value: unknown): value is string => {
  if (typeof value !== "string" || !value.trim()) return false;
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
};

// Keep the public site renderable when deployment variables are missing or malformed.
// Supabase-backed features will report their request errors instead of crashing the app at import time.
const SUPABASE_URL = isHttpUrl(configuredSupabaseUrl)
  ? configuredSupabaseUrl
  : "https://placeholder.supabase.co";
const SUPABASE_ANON_KEY = configuredSupabaseKey?.trim() || "placeholder-anon-key";

if (!isHttpUrl(configuredSupabaseUrl)) {
  console.warn("[v0] Supabase URL is missing or invalid; using a safe placeholder client.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use untyped client to avoid strict table generics until Database types are generated
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
